[groq]
api_key = "gsk_xxxxx_tu_key_aquí"

[serpapi]
api_key = "tu_key_de_serper_aquí"  # Recomiendo usar Serper (serper.dev)

[supabase]
url = "https://abc.def.supabase.co"
key = "tu_clave_anon_de_supabase_aquí"

[huggingface]
token = "hf_xxxxx_tu_token_hf_aquí"